module.exports = {
  'import/extensions': [
    'error',
    'ignorePackages',
    {
      js: 'never',
      jsx: 'never',
      mjs: 'never',
      ts: 'never',
      tsx: 'never',
    },
  ],
  'import/no-extraneous-dependencies': [
    'error',
    {
      devDependencies: [
        '.*rc.js',
        '*.{config,setup}.js',
        '**/test.{js,jsx}',
        '**/test-*.{js,jsx}',
        '**/*{.,_}{test,spec}.{js,jsx}',
        '**/test/**',
        '**/tests/**',
        '**/spec/**',
        '**/__tests__/**',
        '**/__mocks__/**',
        '**/cypress/**',
        '**/jest.config.js',
        '**/jest.setup.js',
        '**/setupTests.js',
        '**/setupProxy.js',
        '**/webpack.config.js',
        '**/webpack.config.*.js',
        '**/rollup.config.js',
        '**/rollup.config.*.js',
        '**/prettier.config.js',
      ],
    },
  ],
  'import/prefer-default-export': 'off',
};
