module.exports = {
  'react/destructuring-assignment': 'off',
  'react/jsx-filename-extension': 'off',
  'react/jsx-fragments': ['error', 'element'],
  'react/jsx-no-bind': 'off',
  'react/jsx-no-leaked-render': 'error',
  'react/jsx-no-target-blank': 'error',
  'react/jsx-pascal-case': [
    'error',
    {
      allowAllCaps: true,
      // https://theme-ui.com/theme-spec#styles
      ignore: [
        'p',
        'a',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'img',
        'pre',
        'code',
        'ol',
        'ul',
        'li',
        'blockquote',
        'hr',
        'em',
        'table',
        'tr',
        'th',
        'td',
        'strong',
        'del',
        'inlineCode',
        'thematicBreak',
        'div',
        'root',
      ],
    },
  ],
  'react/jsx-props-no-spreading': 'off',
  'react/function-component-definition': [
    'error',
    {
      namedComponents: 'function-declaration',
      unnamedComponents: 'arrow-function',
    },
  ],
  'react/no-namespace': 'error',
  'react/require-default-props': [
    'error',
    {
      functions: 'defaultArguments',
    },
  ],
  'react/self-closing-comp': 'off',
  'react/state-in-constructor': 'off',
  'react/static-property-placement': 'off',
};
