version: 2.1

orbs:
  node: circleci/node@4.8.1

defaults: &defaults
  executor:
    name: node/default
    tag: lts

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn validate
      - persist_to_workspace:
          root: ~/
          paths:
            - project
      - run:
          name: Clone a real repository
          command:
            git clone --single-branch --depth 1
            https://github.com/wKovacs64/use-stepper.git ~/example
      - run:
          name: Install package in the real repository
          command:
            npx yalc publish && cd ~/example && npx yalc add --dev
            eslint-plugin-wkovacs64 && yarn --ignore-scripts
      - run:
          name: Lint the real repository
          command: cd ~/example && yarn lint
  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn semantic-release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          context:
            - release
            - publish
          requires:
            - test
          filters:
            branches:
              only: master
